{% set version = "3.1.2" %}

package:
  name: python-socketio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-socketio/python-socketio-{{ version }}.tar.gz
  sha256: aa702157694d55a743fb6f1cc0bd1af58fbfda8a7d71d747d4b12d6dac29cab3

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - six >=1.9.0
    - python-engineio >=3.0.0

test:
  imports:
    - socketio
    - socketio.base_manager
    - socketio.kombu_manager
    - socketio.middleware
    - socketio.namespace
    - socketio.packet
    - socketio.pubsub_manager
    - socketio.redis_manager
    - socketio.server

about:
  home: https://github.com/miguelgrinberg/python-socketio/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Socket.IO server'
  doc_url: https://python-socketio.readthedocs.io/
  dev_url: https://github.com/miguelgrinberg/python-socketio/


extra:
  recipe-maintainers:
    - pmlandwehr
