{% set name = "python-socketio" %}
{% set version = "3.1.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "aa702157694d55a743fb6f1cc0bd1af58fbfda8a7d71d747d4b12d6dac29cab3" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.9.0
    - python-engineio >=1.2.1

test:
  imports:
    - socketio
    - socketio.base_manager
    - socketio.kombu_manager
    - socketio.middleware
    - socketio.namespace
    - socketio.packet
    - socketio.pubsub_manager
    - socketio.redis_manager
    - socketio.server

about:
  home: https://github.com/miguelgrinberg/python-socketio/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Socket.IO server'
  doc_url: https://python-socketio.readthedocs.io/
  dev_url: https://github.com/miguelgrinberg/python-socketio/


extra:
  recipe-maintainers:
    - pmlandwehr
