travis:
  secure:
    BINSTAR_TOKEN: wjV+vn9RuSHbuWQ6jJSz6OQWICGSUnhFeebhWcmw6Xa63MufEjrBr+qCy5iEpXyph9WZVUaK7hDXb6Oelrm+74L7kDo2kK51BdlNz51P6dmq5CVGftCh9p5VDiKo7jXjUlEmOwmYsFTXcjK/DR3T9af0W34oyQKKkud/4V2pQB12o0F/Qgk8p54puOr6TGXZg5XEHEpdlaHwwA1clShAo1G3TMQHa9MHMBLtq01AKIOQtEfDMkneagmjhJyjcEKCRnH4BZPUtQx24+vcujfz5kzPkJot29AxjAptMH4qjn1JiOfrLB9e9oOsBXdBgGyS4sGR26nXVxHrF/qp5D4fG3uSoid++v6Qfhl+OwQ/onoFnqaUBAtazEcFo0VVlTirMQ6YFeiCaNJZ/iyU0mVoE3wWFdL7qnsUN0QgFRs+kl5vrh4egfctXmUCi1VcEk8cWdxMNhrzOMjtYkiaVO5O+RDj/4RA5zIlzjDEkprCSwLXrsjq8JU2vZQ1n4qlRqa7dLGzLE/nMeHXu0r7vQOtPpTzhNQzFmU6t+dFz0c5crJZw3r+1Csp7PLOo3ck/edoPc2GcsaAVKRsGM26nZOPtBKdnsE0BBlIwDTntdztWMrJuiraNICJ5gfWjHhoZhozuxc6rS7BhpAcTgI0rS69YEMs5AgKA/2juxhNPsZBnk0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
